-- Expand default exercise library for testing.
-- Naming: full words "Kettlebell" / "Dumbbell" (consistent with existing seeds).

INSERT INTO exercises (name, equipment_type, is_default) VALUES
  -- Barbell
  ('Hang Snatch', 'barbell', true),
  ('Hang Power Clean', 'barbell', true),
  ('Hang Power Snatch', 'barbell', true),
  ('Squat Clean', 'barbell', true),
  ('Squat Snatch', 'barbell', true),
  ('Push Jerk', 'barbell', true),
  ('Split Jerk', 'barbell', true),
  ('Close-Grip Bench Press', 'barbell', true),
  ('Floor Press', 'barbell', true),
  ('Landmine Press', 'barbell', true),
  ('Box Squat', 'barbell', true),
  ('Bulgarian Split Squat', 'barbell', true),
  ('Trap Bar Deadlift', 'barbell', true),
  ('Snatch-Grip Deadlift', 'barbell', true),
  ('Front Rack Lunges', 'barbell', true),
  ('Back Rack Lunges', 'barbell', true),

  -- Kettlebell
  ('Kettlebell Snatch', 'kettlebell', true),
  ('Kettlebell Clean', 'kettlebell', true),
  ('Kettlebell Clean & Jerk', 'kettlebell', true),
  ('Kettlebell Push Press', 'kettlebell', true),
  ('Kettlebell Press', 'kettlebell', true),
  ('Kettlebell Swing', 'kettlebell', true),
  ('Kettlebell Front Squat', 'kettlebell', true),
  ('Kettlebell Turkish Get-Up', 'kettlebell', true),
  ('Kettlebell Windmill', 'kettlebell', true),
  ('Kettlebell Romanian Deadlift', 'kettlebell', true),
  ('Kettlebell Lunges', 'kettlebell', true),
  ('Kettlebell Thruster', 'kettlebell', true),
  ('Kettlebell Row', 'kettlebell', true),
  ('Kettlebell Gorilla Row', 'kettlebell', true),

  -- Dumbbell
  ('Dumbbell Snatch', 'dumbbell', true),
  ('Dumbbell Clean', 'dumbbell', true),
  ('Dumbbell Clean & Jerk', 'dumbbell', true),
  ('Dumbbell Push Press', 'dumbbell', true),
  ('Dumbbell Shoulder Press', 'dumbbell', true),
  ('Dumbbell Row', 'dumbbell', true),
  ('Dumbbell Gorilla Row', 'dumbbell', true),
  ('Dumbbell Lunges', 'dumbbell', true),
  ('Dumbbell Romanian Deadlift', 'dumbbell', true),
  ('Dumbbell Thruster', 'dumbbell', true),
  ('Dumbbell Bulgarian Split Squat', 'dumbbell', true),
  ('Dumbbell Bicep Curl', 'dumbbell', true),
  ('Dumbbell Lateral Raise', 'dumbbell', true),

  -- Bodyweight
  ('Push-Up', 'bodyweight', true),
  ('Ring Dips', 'bodyweight', true),
  ('Ring Row', 'bodyweight', true),
  ('Bar Muscle-Up', 'bodyweight', true),
  ('Ring Muscle-Up', 'bodyweight', true),
  ('Handstand Push-Up', 'bodyweight', true),
  ('Pistol Squat', 'bodyweight', true),
  ('Air Squat', 'bodyweight', true),
  ('Box Jump', 'bodyweight', true),
  ('Sit-Up', 'bodyweight', true),
  ('V-Up', 'bodyweight', true),
  ('Hanging Leg Raise', 'bodyweight', true),
  ('Wall Walk', 'bodyweight', true),

  -- Machine
  ('Lat Pulldown', 'machine', true),
  ('Seated Cable Row', 'machine', true),
  ('Leg Press', 'machine', true),
  ('Leg Extension', 'machine', true),
  ('Leg Curl', 'machine', true),
  ('Hack Squat', 'machine', true),
  ('Chest Press Machine', 'machine', true),
  ('Shoulder Press Machine', 'machine', true),
  ('Pec Deck', 'machine', true),
  ('Cable Triceps Pushdown', 'machine', true),
  ('Cable Bicep Curl', 'machine', true),
  ('Cable Lateral Raise', 'machine', true),
  ('Cable Fly', 'machine', true),
  ('Calf Raise Machine', 'machine', true),
  ('Smith Machine Squat', 'machine', true),
  ('Assisted Pull-Up Machine', 'machine', true);
